auth:
  token_expiry: 3600
  secret_key: ""

logging:
  level: INFO
  file: logs/security.log

policies:
  policies:
    - name: "allow_internal_communication"
      conditions:
        source_agent: {"regex": "^internal_.*"}
        target_agent: {"regex": "^internal_.*"}
      effect: "allow"
      priority: 100

    - name: "allow_basic_tasks"
      conditions:
        action_type: "execute_task"
        resource:
          type: {"in": ["read", "process"]}
      effect: "allow"
      priority: 80

    - name: "allow_research_tasks"
      conditions:
        action_type: "execute_task"
        agent_id: "researcher"
      effect: "allow"
      priority: 70

    - name: "allow_agent_communication"
      conditions:
        action_type: "send_message"
        source_agent: {"regex": ".*"}
      effect: "allow"
      priority: 60

    - name: "default_deny"
      conditions: {}
      effect: "deny"
      priority: 0